export const PROJECTS_DATA = [
    {
        id: 1,
        titleFr: 'تزويد مركز الفضل للتنمية البشرية بالطاقة الشمسية ببركان', 
        titleAr: 'تزويد مركز الفضل للتنمية البشرية بالطاقة الشمسية ببركان',
        category: 'القطاع الماء الصالح للشرب والكهرباء',
        imageUrl: 'assets/images/projets_extracted/image4.jpeg',
        gallery: ["assets/images/projets_extracted/image4.jpeg", "assets/images/projets_extracted/image3.jpeg"],
        descriptionFr: 'تزويد مركز الفضل للتنمية البشرية بالطاقة الشمسية ببركان',
        descriptionAr: 'تزويد مركز الفضل للتنمية البشرية بالطاقة الشمسية ببركان',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 2,
        titleFr: 'مشروع بناء دار الثقافة بركان', 
        titleAr: 'مشروع بناء دار الثقافة بركان',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image6.jpeg',
        gallery: ["assets/images/projets_extracted/image6.jpeg", "assets/images/projets_extracted/image5.jpeg"],
        descriptionFr: 'مشروع بناء دار الثقافة بركان',
        descriptionAr: 'مشروع بناء دار الثقافة بركان',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: true
    },
    {
        id: 3,
        titleFr: 'مشروع بناء دار الثقافة بركان', 
        titleAr: 'مشروع بناء دار الثقافة بركان',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image8.jpeg',
        gallery: ["assets/images/projets_extracted/image8.jpeg", "assets/images/projets_extracted/image7.jpeg", "assets/images/projets_extracted/image9.jpeg"],
        descriptionFr: 'مشروع بناء دار الثقافة بركان',
        descriptionAr: 'مشروع بناء دار الثقافة بركان',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: true
    },
    {
        id: 4,
        titleFr: 'الحماية من الفياضات بمركز سيدي سليمان شراعة', 
        titleAr: 'الحماية من الفياضات بمركز سيدي سليمان شراعة',
        category: 'القطاع البيئة',
        imageUrl: 'assets/images/projets_extracted/image11.jpeg',
        gallery: ["assets/images/projets_extracted/image11.jpeg", "assets/images/projets_extracted/image10.jpeg"],
        descriptionFr: 'الحماية من الفياضات بمركز سيدي سليمان شراعة',
        descriptionAr: 'الحماية من الفياضات بمركز سيدي سليمان شراعة',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 5,
        titleFr: 'بناء النواة الجامعية', 
        titleAr: 'بناء النواة الجامعية',
        category: 'القطاع التعليم و النقل المدرسي',
        imageUrl: 'assets/images/projets_extracted/image13.jpeg',
        gallery: ["assets/images/projets_extracted/image13.jpeg", "assets/images/projets_extracted/image12.png", "assets/images/projets_extracted/image14.jpeg"],
        descriptionFr: 'بناء النواة الجامعية',
        descriptionAr: 'بناء النواة الجامعية',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 6,
        titleFr: 'أشغال الإنارة العمومية لمركز', 
        titleAr: 'أشغال الإنارة العمومية لمركز',
        category: 'القطاع الماء الصالح للشرب والكهرباء',
        imageUrl: 'assets/images/projets_extracted/image16.jpeg',
        gallery: ["assets/images/projets_extracted/image16.jpeg", "assets/images/projets_extracted/image15.jpeg", "assets/images/projets_extracted/image17.jpeg"],
        descriptionFr: 'أشغال الإنارة العمومية لمركز',
        descriptionAr: 'أشغال الإنارة العمومية لمركز لمريس أغبال',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 7,
        titleFr: 'أشغال تأهيل مركز أغبال', 
        titleAr: 'أشغال تأهيل مركز أغبال',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image19.jpeg',
        gallery: ["assets/images/projets_extracted/image19.jpeg", "assets/images/projets_extracted/image18.jpeg", "assets/images/projets_extracted/image21.jpeg", "assets/images/projets_extracted/image20.jpeg"],
        descriptionFr: 'أشغال تأهيل مركز أغبال',
        descriptionAr: 'أشغال تأهيل مركز أغبال',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 8,
        titleFr: 'أشغال تأهيل مركز أغبال', 
        titleAr: 'أشغال تأهيل مركز أغبال',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image23.jpeg',
        gallery: ["assets/images/projets_extracted/image23.jpeg", "assets/images/projets_extracted/image22.jpeg"],
        descriptionFr: 'أشغال تأهيل مركز أغبال',
        descriptionAr: 'أشغال تأهيل مركز أغبال',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 9,
        titleFr: 'تهيئة فضاءات لعرض وبيع المنتوجات المحلية بتافوغالت', 
        titleAr: 'تهيئة فضاءات لعرض وبيع المنتوجات المحلية بتافوغالت',
        category: 'القطاع التشغيل و التنمية الإقتصادية',
        imageUrl: 'assets/images/projets_extracted/image24.jpeg',
        gallery: ["assets/images/projets_extracted/image24.jpeg"],
        descriptionFr: 'تهيئة فضاءات لعرض وبيع المنتوجات المحلية بتافوغالت',
        descriptionAr: 'تهيئة فضاءات لعرض وبيع المنتوجات المحلية بتافوغالت',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 10,
        titleFr: 'تهيئة فضاءات لعرض وبيع المنتوجات المحلية بتافوغالت', 
        titleAr: 'تهيئة فضاءات لعرض وبيع المنتوجات المحلية بتافوغالت',
        category: 'القطاع التشغيل و التنمية الإقتصادية',
        imageUrl: 'assets/images/projets_extracted/image26.jpeg',
        gallery: ["assets/images/projets_extracted/image26.jpeg", "assets/images/projets_extracted/image25.jpeg"],
        descriptionFr: 'تهيئة فضاءات لعرض وبيع المنتوجات المحلية بتافوغالت',
        descriptionAr: 'تهيئة فضاءات لعرض وبيع المنتوجات المحلية بتافوغالت',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 11,
        titleFr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف', 
        titleAr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        category: 'القطاع الطرق والمسالك',
        imageUrl: 'assets/images/projets_extracted/image28.jpeg',
        gallery: ["assets/images/projets_extracted/image28.jpeg", "assets/images/projets_extracted/image27.jpeg", "assets/images/projets_extracted/image29.jpeg"],
        descriptionFr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        descriptionAr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 12,
        titleFr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف', 
        titleAr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        category: 'القطاع الطرق والمسالك',
        imageUrl: 'assets/images/projets_extracted/image31.jpeg',
        gallery: ["assets/images/projets_extracted/image31.jpeg", "assets/images/projets_extracted/image30.jpeg"],
        descriptionFr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        descriptionAr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 13,
        titleFr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف', 
        titleAr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        category: 'القطاع الطرق والمسالك',
        imageUrl: 'assets/images/projets_extracted/image33.jpeg',
        gallery: ["assets/images/projets_extracted/image33.jpeg", "assets/images/projets_extracted/image32.jpeg"],
        descriptionFr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        descriptionAr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 14,
        titleFr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف', 
        titleAr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        category: 'القطاع الطرق والمسالك',
        imageUrl: 'assets/images/projets_extracted/image35.jpeg',
        gallery: ["assets/images/projets_extracted/image35.jpeg", "assets/images/projets_extracted/image34.jpeg", "assets/images/projets_extracted/image36.jpeg"],
        descriptionFr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        descriptionAr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 15,
        titleFr: 'المشروع', 
        titleAr: 'المشروع',
        category: 'القطاع البيئة',
        imageUrl: 'assets/images/projets_extracted/image38.jpeg',
        gallery: ["assets/images/projets_extracted/image38.jpeg", "assets/images/projets_extracted/image37.jpeg"],
        descriptionFr: 'المشروع',
        descriptionAr: 'المشروع المبلغ الإجمالي مساهمة المجلس الاقليمي تقدم الأشغال الحماية من الفياضات بمركز سيدي بوهرية "بناء قناطر" 1 280 000,00 المجلس الاقليمي : 1,28 MDH 100% جماعة سيدي بوهرية',
        cost: '1 280 000,00',
        location: 'جماعة',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 16,
        titleFr: 'الحماية من الفياضات بمركز سيدي بوهرية "بناء قناطر"', 
        titleAr: 'الحماية من الفياضات بمركز سيدي بوهرية "بناء قناطر"',
        category: 'القطاع البيئة',
        imageUrl: 'assets/images/projets_extracted/image40.jpeg',
        gallery: ["assets/images/projets_extracted/image40.jpeg", "assets/images/projets_extracted/image39.jpeg"],
        descriptionFr: 'الحماية من الفياضات بمركز سيدي بوهرية "بناء قناطر"',
        descriptionAr: 'الحماية من الفياضات بمركز سيدي بوهرية "بناء قناطر"',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 17,
        titleFr: 'تزويد دوار', 
        titleAr: 'تزويد دوار',
        category: 'القطاع الماء الصالح للشرب والكهرباء',
        imageUrl: 'assets/images/projets_extracted/image42.jpeg',
        gallery: ["assets/images/projets_extracted/image42.jpeg", "assets/images/projets_extracted/image41.jpeg"],
        descriptionFr: 'تزويد دوار',
        descriptionAr: 'تزويد دوار تعيشونت 2 و دوار تزغين  بوكشوط بالماء الصالح للشرب',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 18,
        titleFr: 'تزويد دوار', 
        titleAr: 'تزويد دوار',
        category: 'القطاع الماء الصالح للشرب والكهرباء',
        imageUrl: 'assets/images/projets_extracted/image44.jpeg',
        gallery: ["assets/images/projets_extracted/image44.jpeg", "assets/images/projets_extracted/image43.jpeg"],
        descriptionFr: 'تزويد دوار',
        descriptionAr: 'تزويد دوار تعيشونت 2 و دوار تزغين  بوكشوط بالماء الصالح للشرب',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 19,
        titleFr: 'تزويد دوار', 
        titleAr: 'تزويد دوار',
        category: 'القطاع الماء الصالح للشرب والكهرباء',
        imageUrl: 'assets/images/projets_extracted/image46.jpeg',
        gallery: ["assets/images/projets_extracted/image46.jpeg", "assets/images/projets_extracted/image45.jpeg", "assets/images/projets_extracted/image47.jpeg"],
        descriptionFr: 'تزويد دوار',
        descriptionAr: 'تزويد دوار جعرة بالماء الصالح للشرب',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 20,
        titleFr: 'المركب التربوي', 
        titleAr: 'المركب التربوي',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image48.jpeg',
        gallery: ["assets/images/projets_extracted/image48.jpeg"],
        descriptionFr: 'المركب التربوي',
        descriptionAr: 'المركب التربوي و الرياضي و الصحي  بجماعة زكزل',
        cost: 'Non spécifié / غير محدد',
        location: 'الصحي  بجماعة زكزل',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 21,
        titleFr: 'أشغال بناء قاعة متعددة الاختصاصات بإعدادية الشويحية', 
        titleAr: 'أشغال بناء قاعة متعددة الاختصاصات بإعدادية الشويحية',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image50.jpeg',
        gallery: ["assets/images/projets_extracted/image50.jpeg", "assets/images/projets_extracted/image49.jpeg"],
        descriptionFr: 'أشغال بناء قاعة متعددة الاختصاصات بإعدادية الشويحية',
        descriptionAr: 'أشغال بناء قاعة متعددة الاختصاصات بإعدادية الشويحية',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 22,
        titleFr: 'أشغال بناء قاعة متعددة الاختصاصات بإعدادية الشويحية', 
        titleAr: 'أشغال بناء قاعة متعددة الاختصاصات بإعدادية الشويحية',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image51.jpeg',
        gallery: ["assets/images/projets_extracted/image51.jpeg"],
        descriptionFr: 'أشغال بناء قاعة متعددة الاختصاصات بإعدادية الشويحية',
        descriptionAr: 'أشغال بناء قاعة متعددة الاختصاصات بإعدادية الشويحية',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 23,
        titleFr: 'أشغال بناء قنطرة', 
        titleAr: 'أشغال بناء قنطرة',
        category: 'القطاع الطرق والمسالك',
        imageUrl: 'assets/images/projets_extracted/image53.jpeg',
        gallery: ["assets/images/projets_extracted/image53.jpeg", "assets/images/projets_extracted/image52.jpeg", "assets/images/projets_extracted/image54.jpeg"],
        descriptionFr: 'أشغال بناء قنطرة',
        descriptionAr: 'أشغال بناء قنطرة  على واد الخميس بدوار بوغريبة',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 24,
        titleFr: 'بناء وتجهيز فضاء النسيج الجمعوي', 
        titleAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image56.jpeg',
        gallery: ["assets/images/projets_extracted/image56.jpeg", "assets/images/projets_extracted/image55.jpeg"],
        descriptionFr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        descriptionAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 25,
        titleFr: 'بناء وتجهيز فضاء النسيج الجمعوي', 
        titleAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image57.jpeg',
        gallery: ["assets/images/projets_extracted/image57.jpeg"],
        descriptionFr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        descriptionAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 26,
        titleFr: 'بناء وتجهيز فضاء النسيج الجمعوي', 
        titleAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image58.jpeg',
        gallery: ["assets/images/projets_extracted/image58.jpeg"],
        descriptionFr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        descriptionAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 27,
        titleFr: 'بناء وتجهيز فضاء النسيج الجمعوي', 
        titleAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image60.jpeg',
        gallery: ["assets/images/projets_extracted/image60.jpeg", "assets/images/projets_extracted/image59.jpeg"],
        descriptionFr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        descriptionAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 28,
        titleFr: 'بناء وتجهيز فضاء النسيج الجمعوي', 
        titleAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image62.jpeg',
        gallery: ["assets/images/projets_extracted/image62.jpeg", "assets/images/projets_extracted/image61.jpeg"],
        descriptionFr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        descriptionAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 29,
        titleFr: 'بناء وتجهيز فضاء النسيج الجمعوي', 
        titleAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image63.jpeg',
        gallery: ["assets/images/projets_extracted/image63.jpeg"],
        descriptionFr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        descriptionAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 30,
        titleFr: 'تزويد ملعب كرة القدم بالكهرباء بجماعة عين الركادة', 
        titleAr: 'تزويد ملعب كرة القدم بالكهرباء بجماعة عين الركادة',
        category: 'القطاع الماء الصالح للشرب والكهرباء',
        imageUrl: 'assets/images/projets_extracted/image65.jpeg',
        gallery: ["assets/images/projets_extracted/image65.jpeg", "assets/images/projets_extracted/image64.jpeg"],
        descriptionFr: 'تزويد ملعب كرة القدم بالكهرباء بجماعة عين الركادة',
        descriptionAr: 'تزويد ملعب كرة القدم بالكهرباء بجماعة عين الركادة',
        cost: 'Non spécifié / غير محدد',
        location: 'تزويد ملعب كرة القدم بالكهرباء بجماعة عين الركادة',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 31,
        titleFr: 'أشغال', 
        titleAr: 'أشغال',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image67.jpeg',
        gallery: ["assets/images/projets_extracted/image67.jpeg", "assets/images/projets_extracted/image66.jpeg"],
        descriptionFr: 'أشغال',
        descriptionAr: 'أشغال الانارة العمومية  شارع محمد الخامس بجماعة أحفير',
        cost: 'Non spécifié / غير محدد',
        location: 'العمومية  شارع محمد الخامس بجماعة أحفير',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 32,
        titleFr: 'أشغال', 
        titleAr: 'أشغال',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image69.jpeg',
        gallery: ["assets/images/projets_extracted/image69.jpeg", "assets/images/projets_extracted/image68.jpeg"],
        descriptionFr: 'أشغال',
        descriptionAr: 'أشغال الانارة العمومية  شارع محمد الخامس بجماعة أحفير',
        cost: 'Non spécifié / غير محدد',
        location: 'العمومية  شارع محمد الخامس بجماعة أحفير',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 33,
        titleFr: 'أشغال التهيئة الخارجية للمؤسسات التعليمية بجماعة أحفير', 
        titleAr: 'أشغال التهيئة الخارجية للمؤسسات التعليمية بجماعة أحفير',
        category: 'القطاع التعليم و النقل المدرسي',
        imageUrl: 'assets/images/projets_extracted/image71.jpeg',
        gallery: ["assets/images/projets_extracted/image71.jpeg", "assets/images/projets_extracted/image70.jpeg"],
        descriptionFr: 'أشغال التهيئة الخارجية للمؤسسات التعليمية بجماعة أحفير',
        descriptionAr: 'أشغال التهيئة الخارجية للمؤسسات التعليمية بجماعة أحفير',
        cost: 'Non spécifié / غير محدد',
        location: 'أشغال التهيئة الخارجية للمؤسسات التعليمية بجماعة أحفير',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 34,
        titleFr: 'أشغال التهيئة الخارجية للمؤسسات التعليمية بجماعة أحفير', 
        titleAr: 'أشغال التهيئة الخارجية للمؤسسات التعليمية بجماعة أحفير',
        category: 'القطاع التعليم و النقل المدرسي',
        imageUrl: 'assets/images/projets_extracted/image73.jpeg',
        gallery: ["assets/images/projets_extracted/image73.jpeg", "assets/images/projets_extracted/image72.jpeg"],
        descriptionFr: 'أشغال التهيئة الخارجية للمؤسسات التعليمية بجماعة أحفير',
        descriptionAr: 'أشغال التهيئة الخارجية للمؤسسات التعليمية بجماعة أحفير',
        cost: 'Non spécifié / غير محدد',
        location: 'أشغال التهيئة الخارجية للمؤسسات التعليمية بجماعة أحفير',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 35,
        titleFr: 'أشغال تزويد دوار تكرورين-سيدي علي بن يخلف بالماء الصالح للشرب جماعة فزوان', 
        titleAr: 'أشغال تزويد دوار تكرورين-سيدي علي بن يخلف بالماء الصالح للشرب جماعة فزوان',
        category: 'القطاع الماء الصالح للشرب والكهرباء',
        imageUrl: 'assets/images/projets_extracted/image75.jpeg',
        gallery: ["assets/images/projets_extracted/image75.jpeg", "assets/images/projets_extracted/image74.jpeg", "assets/images/projets_extracted/image77.jpeg", "assets/images/projets_extracted/image76.jpeg"],
        descriptionFr: 'أشغال تزويد دوار تكرورين-سيدي علي بن يخلف بالماء الصالح للشرب جماعة فزوان',
        descriptionAr: 'أشغال تزويد دوار تكرورين-سيدي علي بن يخلف بالماء الصالح للشرب جماعة فزوان سيدي علي بن يخلف',
        cost: 'Non spécifié / غير محدد',
        location: 'أشغال تزويد دوار تكرورين-سيدي علي بن يخلف بالماء الصالح للشرب جماعة فزوان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 36,
        titleFr: 'انجاز المسلك المؤدي من عين', 
        titleAr: 'انجاز المسلك المؤدي من عين',
        category: 'القطاع الطرق والمسالك',
        imageUrl: 'assets/images/projets_extracted/image79.jpeg',
        gallery: ["assets/images/projets_extracted/image79.jpeg", "assets/images/projets_extracted/image78.jpeg"],
        descriptionFr: 'انجاز المسلك المؤدي من عين',
        descriptionAr: 'انجاز المسلك المؤدي من عين الزبدة إلى بني موسى بجماعة مداغ',
        cost: 'Non spécifié / غير محدد',
        location: 'إلى بني موسى بجماعة مداغ',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 37,
        titleFr: 'انجاز المسلك المؤدي من عين', 
        titleAr: 'انجاز المسلك المؤدي من عين',
        category: 'القطاع الطرق والمسالك',
        imageUrl: 'assets/images/projets_extracted/image81.jpeg',
        gallery: ["assets/images/projets_extracted/image81.jpeg", "assets/images/projets_extracted/image80.jpeg"],
        descriptionFr: 'انجاز المسلك المؤدي من عين',
        descriptionAr: 'انجاز المسلك المؤدي من عين الزبدة إلى بني موسى بجماعة مداغ',
        cost: 'Non spécifié / غير محدد',
        location: 'إلى بني موسى بجماعة مداغ',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 38,
        titleFr: 'تمويل', 
        titleAr: 'تمويل',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image83.jpeg',
        gallery: ["assets/images/projets_extracted/image83.jpeg", "assets/images/projets_extracted/image82.jpeg"],
        descriptionFr: 'تمويل',
        descriptionAr: 'تمويل و فتح و تهيئة المسالك القروية',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 39,
        titleFr: 'تمويل', 
        titleAr: 'تمويل',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image85.jpeg',
        gallery: ["assets/images/projets_extracted/image85.jpeg", "assets/images/projets_extracted/image84.jpeg"],
        descriptionFr: 'تمويل',
        descriptionAr: 'تمويل و فتح و تهيئة المسالك القروية',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 40,
        titleFr: 'تمويل', 
        titleAr: 'تمويل',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image86.jpeg',
        gallery: ["assets/images/projets_extracted/image86.jpeg"],
        descriptionFr: 'تمويل',
        descriptionAr: 'تمويل و فتح و تهيئة المسالك القروية',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 41,
        titleFr: 'تمويل', 
        titleAr: 'تمويل',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image88.jpeg',
        gallery: ["assets/images/projets_extracted/image88.jpeg", "assets/images/projets_extracted/image87.jpeg"],
        descriptionFr: 'تمويل',
        descriptionAr: 'تمويل و فتح و تهيئة المسالك القروية',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 42,
        titleFr: 'تمويل', 
        titleAr: 'تمويل',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image90.jpeg',
        gallery: ["assets/images/projets_extracted/image90.jpeg", "assets/images/projets_extracted/image89.jpeg"],
        descriptionFr: 'تمويل',
        descriptionAr: 'تمويل و فتح و تهيئة المسالك القروية',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 43,
        titleFr: 'تمويل', 
        titleAr: 'تمويل',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image92.jpeg',
        gallery: ["assets/images/projets_extracted/image92.jpeg", "assets/images/projets_extracted/image91.jpeg"],
        descriptionFr: 'تمويل',
        descriptionAr: 'تمويل و فتح و تهيئة المسالك القروية',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 44,
        titleFr: 'عملية', 
        titleAr: 'عملية',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image94.jpeg',
        gallery: ["assets/images/projets_extracted/image94.jpeg", "assets/images/projets_extracted/image93.jpeg", "assets/images/projets_extracted/image95.jpeg"],
        descriptionFr: 'عملية',
        descriptionAr: 'عملية تتبع وتسيير أشغال تنقية واد شراعة وواد ورطاس ',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 45,
        titleFr: 'عملية', 
        titleAr: 'عملية',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image96.jpeg',
        gallery: ["assets/images/projets_extracted/image96.jpeg"],
        descriptionFr: 'عملية',
        descriptionAr: 'عملية تتبع وتسيير أشغال تنقية واد شراعة وواد ورطاس ',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 46,
        titleFr: 'اقتناء سيارة نفعية لفائدة نوميديا', 
        titleAr: 'اقتناء سيارة نفعية لفائدة نوميديا',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image97.jpeg',
        gallery: ["assets/images/projets_extracted/image97.jpeg"],
        descriptionFr: 'اقتناء سيارة نفعية لفائدة نوميديا',
        descriptionAr: 'اقتناء سيارة نفعية لفائدة نوميديا',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 47,
        titleFr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان', 
        titleAr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        category: 'القطاع الصحة وحفظ الصحة',
        imageUrl: 'assets/images/projets_extracted/image99.jpeg',
        gallery: ["assets/images/projets_extracted/image99.jpeg", "assets/images/projets_extracted/image98.jpeg"],
        descriptionFr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        descriptionAr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 48,
        titleFr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان', 
        titleAr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        category: 'القطاع الصحة وحفظ الصحة',
        imageUrl: 'assets/images/projets_extracted/image101.jpeg',
        gallery: ["assets/images/projets_extracted/image101.jpeg", "assets/images/projets_extracted/image100.jpeg"],
        descriptionFr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        descriptionAr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 49,
        titleFr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان', 
        titleAr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        category: 'القطاع الصحة وحفظ الصحة',
        imageUrl: 'assets/images/projets_extracted/image103.jpeg',
        gallery: ["assets/images/projets_extracted/image103.jpeg", "assets/images/projets_extracted/image102.jpeg"],
        descriptionFr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        descriptionAr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 50,
        titleFr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان', 
        titleAr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        category: 'القطاع الصحة وحفظ الصحة',
        imageUrl: 'assets/images/projets_extracted/image105.jpeg',
        gallery: ["assets/images/projets_extracted/image105.jpeg", "assets/images/projets_extracted/image104.jpeg"],
        descriptionFr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        descriptionAr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 51,
        titleFr: 'بناء قنطرة على واد البسباس دوار اولاد الحاج جماعة زكزل', 
        titleAr: 'بناء قنطرة على واد البسباس دوار اولاد الحاج جماعة زكزل',
        category: 'القطاع الطرق والمسالك',
        imageUrl: 'assets/images/projets_extracted/image107.jpeg',
        gallery: ["assets/images/projets_extracted/image107.jpeg", "assets/images/projets_extracted/image106.jpeg"],
        descriptionFr: 'بناء قنطرة على واد البسباس دوار اولاد الحاج جماعة زكزل',
        descriptionAr: 'بناء قنطرة على واد البسباس دوار اولاد الحاج جماعة زكزل ا لقنطرة بعد القن طرة قبل',
        cost: 'Non spécifié / غير محدد',
        location: 'بناء قنطرة على واد البسباس دوار اولاد الحاج جماعة زكزل',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 52,
        titleFr: 'تزويد', 
        titleAr: 'تزويد',
        category: 'القطاع الماء الصالح للشرب والكهرباء',
        imageUrl: 'assets/images/projets_extracted/image109.jpeg',
        gallery: ["assets/images/projets_extracted/image109.jpeg", "assets/images/projets_extracted/image108.jpeg", "assets/images/projets_extracted/image110.jpeg"],
        descriptionFr: 'تزويد',
        descriptionAr: 'تزويد  دوار  الزعارة لوطا بالماء الشروب بجماعة بوغريبة',
        cost: 'Non spécifié / غير محدد',
        location: 'الزعارة لوطا بالماء الشروب بجماعة',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 53,
        titleFr: 'اقتناء 10 حافلات للنقل المدرسي لفائدة المجلس الإقليمي لبركان', 
        titleAr: 'اقتناء 10 حافلات للنقل المدرسي لفائدة المجلس الإقليمي لبركان',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image112.png',
        gallery: ["assets/images/projets_extracted/image112.png", "assets/images/projets_extracted/image111.jpeg"],
        descriptionFr: 'اقتناء 10 حافلات للنقل المدرسي لفائدة المجلس الإقليمي لبركان',
        descriptionAr: 'اقتناء 10 حافلات للنقل المدرسي لفائدة المجلس الإقليمي لبركان',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 54,
        titleFr: 'انجاز', 
        titleAr: 'انجاز',
        category: 'القطاع الطرق والمسالك',
        imageUrl: 'assets/images/projets_extracted/image114.jpeg',
        gallery: ["assets/images/projets_extracted/image114.jpeg", "assets/images/projets_extracted/image113.jpeg", "assets/images/projets_extracted/image116.jpeg", "assets/images/projets_extracted/image115.jpeg"],
        descriptionFr: 'انجاز',
        descriptionAr: 'انجاز منشأة فنية على واد ورطاس الرابطة بين حي ورطاس و برج واولوت الدراسة  % 100',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 55,
        titleFr: 'مشروع بناء دار الثقافة بركان', 
        titleAr: 'مشروع بناء دار الثقافة بركان',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image117.jpeg',
        gallery: ["assets/images/projets_extracted/image117.jpeg"],
        descriptionFr: 'مشروع بناء دار الثقافة بركان',
        descriptionAr: 'مشروع بناء دار الثقافة بركان',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: true
    },
    {
        id: 56,
        titleFr: 'مشروع بناء دار الثقافة بركان', 
        titleAr: 'مشروع بناء دار الثقافة بركان',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image118.jpeg',
        gallery: ["assets/images/projets_extracted/image118.jpeg"],
        descriptionFr: 'مشروع بناء دار الثقافة بركان',
        descriptionAr: 'مشروع بناء دار الثقافة بركان',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: true
    },
    {
        id: 57,
        titleFr: 'مشروع بناء دار الثقافة بركان', 
        titleAr: 'مشروع بناء دار الثقافة بركان',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image120.jpeg',
        gallery: ["assets/images/projets_extracted/image120.jpeg", "assets/images/projets_extracted/image119.jpeg", "assets/images/projets_extracted/image121.jpeg"],
        descriptionFr: 'مشروع بناء دار الثقافة بركان',
        descriptionAr: 'مشروع بناء دار الثقافة بركان',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: true
    },
    {
        id: 58,
        titleFr: 'مشروع بناء دار الثقافة بركان', 
        titleAr: 'مشروع بناء دار الثقافة بركان',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image123.jpeg',
        gallery: ["assets/images/projets_extracted/image123.jpeg", "assets/images/projets_extracted/image122.jpeg"],
        descriptionFr: 'مشروع بناء دار الثقافة بركان',
        descriptionAr: 'مشروع بناء دار الثقافة بركان',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: true
    },
    {
        id: 59,
        titleFr: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل', 
        titleAr: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image124.jpeg',
        gallery: ["assets/images/projets_extracted/image124.jpeg"],
        descriptionFr: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل',
        descriptionAr: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل',
        cost: 'Non spécifié / غير محدد',
        location: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 60,
        titleFr: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل', 
        titleAr: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image126.jpeg',
        gallery: ["assets/images/projets_extracted/image126.jpeg", "assets/images/projets_extracted/image125.jpeg"],
        descriptionFr: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل',
        descriptionAr: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل',
        cost: 'Non spécifié / غير محدد',
        location: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 61,
        titleFr: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل', 
        titleAr: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image128.jpeg',
        gallery: ["assets/images/projets_extracted/image128.jpeg", "assets/images/projets_extracted/image127.jpeg"],
        descriptionFr: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل',
        descriptionAr: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل',
        cost: 'Non spécifié / غير محدد',
        location: 'بناء و تجهيز  المركب التربوي و الرياضي و الصحي  بجماعة زكزل',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 62,
        titleFr: 'تهيئة المسالك بالإقليم', 
        titleAr: 'تهيئة المسالك بالإقليم',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image130.jpeg',
        gallery: ["assets/images/projets_extracted/image130.jpeg", "assets/images/projets_extracted/image129.jpeg", "assets/images/projets_extracted/image131.jpeg"],
        descriptionFr: 'تهيئة المسالك بالإقليم',
        descriptionAr: 'تهيئة المسالك بالإقليم',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 63,
        titleFr: 'تهيئة المسالك بالإقليم', 
        titleAr: 'تهيئة المسالك بالإقليم',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image133.jpeg',
        gallery: ["assets/images/projets_extracted/image133.jpeg", "assets/images/projets_extracted/image132.jpeg", "assets/images/projets_extracted/image134.jpeg"],
        descriptionFr: 'تهيئة المسالك بالإقليم',
        descriptionAr: 'تهيئة المسالك بالإقليم',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 64,
        titleFr: 'تهيئة المسالك و تنقية', 
        titleAr: 'تهيئة المسالك و تنقية',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image136.jpeg',
        gallery: ["assets/images/projets_extracted/image136.jpeg", "assets/images/projets_extracted/image135.jpeg"],
        descriptionFr: 'تهيئة المسالك و تنقية',
        descriptionAr: 'تهيئة المسالك و تنقية  النقط  السوداء بالإقليم',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 65,
        titleFr: 'تهيئة المسالك و تنقية', 
        titleAr: 'تهيئة المسالك و تنقية',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image138.jpeg',
        gallery: ["assets/images/projets_extracted/image138.jpeg", "assets/images/projets_extracted/image137.jpeg"],
        descriptionFr: 'تهيئة المسالك و تنقية',
        descriptionAr: 'تهيئة المسالك و تنقية  النقط  السوداء بالإقليم',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 66,
        titleFr: 'تهيئة المسالك وتنقية', 
        titleAr: 'تهيئة المسالك وتنقية',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image140.jpeg',
        gallery: ["assets/images/projets_extracted/image140.jpeg", "assets/images/projets_extracted/image139.jpeg"],
        descriptionFr: 'تهيئة المسالك وتنقية',
        descriptionAr: 'تهيئة المسالك وتنقية  النقط  السوداء بالإقليم',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 67,
        titleFr: 'تهيئة المسالك و تنقية', 
        titleAr: 'تهيئة المسالك و تنقية',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image142.jpeg',
        gallery: ["assets/images/projets_extracted/image142.jpeg", "assets/images/projets_extracted/image141.jpeg"],
        descriptionFr: 'تهيئة المسالك و تنقية',
        descriptionAr: 'تهيئة المسالك و تنقية  النقط  السوداء بالإقليم',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    },
    {
        id: 68,
        titleFr: 'تهيئة المسالك و تنقية', 
        titleAr: 'تهيئة المسالك و تنقية',
        category: 'القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image136.jpeg',
        gallery: ["assets/images/projets_extracted/image136.jpeg", "assets/images/projets_extracted/image143.jpeg"],
        descriptionFr: 'تهيئة المسالك و تنقية',
        descriptionAr: 'تهيئة المسالك و تنقية  النقط  السوداء بالإقليم',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Achevé',
        isMain: false
    }
];