import { Routes } from '@angular/router';
import { SESSION_DATA } from './session-detail/sessions-data';

// ── Session routes ────────────────────────────────────────────────────────────
// All session detail pages are handled by a single component.
// Content comes from session-detail/sessions-data.ts (generated by extract-sessions.js).

const sessionLoader = () =>
    import('./session-detail/session-detail.component').then(m => m.SessionDetailComponent);

const sessionRoutes: Routes = SESSION_DATA.flatMap(s => [
    { path: s.slug,            loadComponent: sessionLoader },
    { path: s.slug + '.html',  loadComponent: sessionLoader }
]);

// ── Non-session routes (keep as individual components) ────────────────────────

const otherRoutes: Routes = [
    { path: 'le-conseil',       loadComponent: () => import('./le-conseil/le-conseil.component').then(m => m.LeConseilComponent) },
    { path: 'organigramme',     loadComponent: () => import('./organigramme/organigramme.component').then(m => m.OrganigrammeComponent) },
    { path: 'organigrames',     loadComponent: () => import('./organigramme/organigramme.component').then(m => m.OrganigrammeComponent) },
    { path: 'organigramme-conseil',     loadComponent: () => import('./organigramme/organigramme.component').then(m => m.OrganigrammeComponent) },
    { path: 'organigramme-administratif', loadComponent: () => import('./organigramme/organigramme.component').then(m => m.OrganigrammeComponent) },
    { path: 'loi-organique',    loadComponent: () => import('./loi-organique/loi-organique.component').then(m => m.LoiOrganiqueComponent) },
    { path: 'sessions',         loadComponent: () => import('./sessions/sessions.component').then(m => m.SessionsComponent) },
    { path: 'sessions-2021',    loadComponent: () => import('./sessions/sessions.component').then(m => m.SessionsComponent) },
    { path: 'sessions-2022',    loadComponent: () => import('./sessions/sessions.component').then(m => m.SessionsComponent) },
    { path: 'sessions-2023',    loadComponent: () => import('./sessions/sessions.component').then(m => m.SessionsComponent) },
    { path: 'sessions-2024',    loadComponent: () => import('./sessions/sessions.component').then(m => m.SessionsComponent) },
    { path: 'sessions-2025',    loadComponent: () => import('./sessions/sessions.component').then(m => m.SessionsComponent) },
    { path: 'sessions-2026',    loadComponent: () => import('./sessions/sessions.component').then(m => m.SessionsComponent) },
    { path: 'projets',          loadComponent: () => import('./projets/projets.component').then(m => m.ProjetsComponent) },
    { path: 'projets/:id',      loadComponent: () => import('./projet-detail/projet-detail.component').then(m => m.ProjetDetailComponent) },
    { path: 'ressources',       loadComponent: () => import('./ressources/ressources.component').then(m => m.RessourcesComponent) },
    { path: 'contact',          loadComponent: () => import('./contact/contact.component').then(m => m.ContactComponent) },
    { path: 'actualites',       loadComponent: () => import('./actualites/actualites.component').then(m => m.ActualitesComponent) },
    { path: 'search',           loadComponent: () => import('./search/search.component').then(m => m.SearchComponent) },
    { path: 'programme-awrach', loadComponent: () => import('./programme-awrach/programme-awrach.component').then(m => m.ProgrammeAwrachComponent) },
    { path: 'programme-ouverture', loadComponent: () => import('./programme-ouverture/programme-ouverture.component').then(m => m.ProgrammeOuvertureComponent) },
    { path: 'rencontre-communication', loadComponent: () => import('./rencontre-communication/rencontre-communication.component').then(m => m.RencontreCommunicationComponent) },
    { path: 'coupe-arabe-detail', loadComponent: () => import('./coupe-arabe-detail/coupe-arabe-detail.component').then(m => m.CoupeArabeDetailComponent) },
    { path: 'ampcpp-detail',    loadComponent: () => import('./ampcpp-detail/ampcpp-detail.component').then(m => m.AmpcppDetailComponent) },
    { path: 'abouab-maftouha',  loadComponent: () => import('./abouab-maftouha/abouab-maftouha.component').then(m => m.AbouabMaftouhaComponent) },
    { path: 'abouab-maftouha-recap', loadComponent: () => import('./abouab-maftouha-recap/abouab-maftouha-recap').then(m => m.AbouabMaftouhaRecapComponent) },
    { path: 'ramadan-mubarak',  loadComponent: () => import('./ramadan-mubarak/ramadan-mubarak.component').then(m => m.RamadanMubarakComponent) },
    { path: 'woman-day',        loadComponent: () => import('./woman-day/woman-day.component').then(m => m.WomanDayComponent) },
    { path: 'new-year',         loadComponent: () => import('./new-year/new-year.component').then(m => m.NewYearComponent) },
    { path: 'home.html',        redirectTo: '' },
    { path: '',                 loadComponent: () => import('./home/home.component').then(m => m.HomeComponent) },
    { path: '**',               redirectTo: '' }
];

export const routes: Routes = [
    ...sessionRoutes,
    ...otherRoutes
];
