import { Project } from './models/project.model';

export const PROJECTS_DATA: Project[] = [
    {
        id: 1,
        titleFr: 'Alimentation solaire du centre Al Fadl',
        titleAr: 'تزويد مركز الفضل للتنمية البشرية بالطاقة الشمسية ببركان',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',
        imageUrl: 'assets/images/projets_extracted/image4.jpeg',
        gallery: ["assets/images/projets_extracted/image4.jpeg", "assets/images/projets_extracted/image3.jpeg"],
        descriptionFr: 'Alimentation du centre Al Fadl pour le Développement Humain en énergie solaire à Berkane',
        descriptionAr: 'تزويد مركز الفضل للتنمية البشرية بالطاقة الشمسية ببركان',
        cost: '120 000,00 DH',
        location: 'Commune de Berkane / جماعة بركان',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 101,
        titleFr: 'Programme Awrach 2',
        titleAr: 'برنامج أوراش 2',
        category: 'دعم القطاع الإجتماعي',
        categoryId: 'emploi',
        imageUrl: 'assets/images/awrach_extracted/slide_11_image_43.png',
        gallery: [],
        descriptionFr: 'Mise en œuvre du programme Awrach 2 pour la création d\'emplois temporaires directs au profit des personnes ayant perdu leur emploi suite à la pandémie COVID-19.',
        descriptionAr: 'تنزيل برنامج أوراش 2 لخلق فرص شغل مؤقتة مباشرة لفائدة الأشخاص الذين فقدوا عملهم جراء جائحة كورونا.',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Réalisé',
        isMain: false
    },

    {
        id: 2,
        titleFr: 'Projet de construction de la Maison de la Culture à Berkane',
        titleAr: 'مشروع بناء دار الثقافة بركان',
        category: 'دعم القطاع الثقافي و الرياضي',
        imageUrl: 'assets/images/projets_extracted/maison_culture_1.jpg',
        gallery: ["assets/images/projets_extracted/maison_culture_1.jpg", "assets/images/projets_extracted/maison_culture_2.jpg", "assets/images/projets_extracted/maison_culture_3.jpg", "assets/images/projets_extracted/maison_culture_4.jpg", "assets/images/projets_extracted/maison_culture_5.jpg", "assets/images/projets_extracted/maison_culture_6.jpg", "assets/images/projets_extracted/maison_culture_7.jpg", "assets/images/projets_extracted/maison_culture_8.jpg"],
        descriptionFr: 'Projet de construction de la Maison de la Culture à Berkane',
        descriptionAr: 'مشروع بناء دار الثقافة بركان',
        cost: '56 282 000,00 DH',
        location: 'Commune de Berkane / جماعة بركان',
        partnersFr: 'Direction Générale des Collectivités Locales / Ministère de la Culture / Agence de l\'Oriental / Conseil Provincial de Berkane / Commune Urbaine de Berkane',
        partnersAr: 'المديرية العامة للجماعات المحلية / وزارة الثقافة / وكالة الجهة الشرقية / المجلس الإقليمي لبركان / الجماعة الحضرية لبركان',
        partnerImages: [
            'assets/images/partners/dgcl.jpeg',
            'assets/images/partners/ministere_culture.jpeg',
            'assets/images/partners/agence_oriental.jpeg',
            'assets/images/partners/conseil_provincial.jpeg',
            'assets/images/partners/commune_berkane.jpeg'
        ],
        status: 'Réalisé',
        isMain: true
    },
    {
        id: 3,
        titleFr: 'Protection contre les inondations au centre de Sidi Slimane Charraa',
        titleAr: 'الحماية من الفيضانات بمركز سيدي سليمان شراعة',
        category: 'دعم القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image11.jpeg',
        gallery: ["assets/images/projets_extracted/image11.jpeg", "assets/images/projets_extracted/image10.jpeg"],
        descriptionFr: 'Protection contre les inondations au centre de Sidi Slimane Charraa',
        descriptionAr: 'الحماية من الفيضانات بمركز سيدي سليمان شراعة',
        cost: '43 000 000,00 DH',
        location: 'Commune Sidi Slimane Charraa / جماعة سيدي سليمان شراعة',
        partnersFr: 'Ministère de l\'Intérieur / Secrétariat d\'Etat chargé de l\'Eau / Ministère de l\'Equipement, du Transport, de la Logistique et de l\'Eau / Conseil de la Région de l\'Oriental / Commune de Sidi Slimane Charraa / Conseil Provincial de Berkane / Office Régional de Mise en Valeur Agricole de la Moulouya',
        partnersAr: 'وزارة الدخلية / كتابة الدولة المكلفة بوزارة التجهيز والنقل واللوجستيك والماء مكلفة بالماء / وزارة التجهيز والنقل واللوجستيك والماء / مجلس جهة الشرق / جماعة سيدي سليمان شراعة / المجلس الإقليمي لبركان / المكتب الجهوي للإستثمار الفلاحي  لملوية',
        partnerImages: [
            'assets/images/partners/ministere_interieur.jpeg',
            'assets/images/partners/ministere_equipement.jpeg',
            'assets/images/partners/commune_sidi_slimane.jpeg',
            'assets/images/partners/conseil_provincial.jpeg',
            'assets/images/partners/ormvam.jpeg'
        ],
        status: 'Réalisé',
        isMain: false
    },

    {
        id: 5,
        titleFr: 'Eclairage public - Centre Lemris Aghbal',
        titleAr: 'أشغال الإنارة العمومية لمركز لمريس أغبال',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',
        imageUrl: 'assets/images/projets_extracted/image16.jpeg',
        gallery: ["assets/images/projets_extracted/image16.jpeg", "assets/images/projets_extracted/image15.jpeg", "assets/images/projets_extracted/image17.jpeg"],
        descriptionFr: 'Travaux d\'éclairage public pour le centre Lemris Aghbal',
        descriptionAr: 'أشغال الإنارة العمومية لمركز لمريس أغبال',
        cost: '459 858,00 DH',
        location: 'Commune Aghbal / جماعة أغبال',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 6,
        titleFr: 'Qualification du centre Aghbal',
        titleAr: 'أشغال تأهيل مركز أغبال',
        category: 'دعم القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image19.jpeg',
        gallery: ["assets/images/projets_extracted/image19.jpeg", "assets/images/projets_extracted/image18.jpeg", "assets/images/projets_extracted/image21.jpeg", "assets/images/projets_extracted/image20.jpeg", "assets/images/projets_extracted/image23.jpeg", "assets/images/projets_extracted/image22.jpeg"],
        descriptionFr: 'Travaux de qualification du centre d\'Aghbal',
        descriptionAr: 'أشغال تأهيل مركز أغبال',
        cost: '3 400 000,00 DH',
        location: 'Commune Aghbal / جماعة أغبال',
        partnersFr: 'Commune Aghbal',
        partnersAr: 'جماعة أغبال',
        partnerImages: ['assets/images/partners/commune_aghbal.jpeg'],
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 7,
        titleFr: 'Espace produits locaux - Tafoughalt',
        titleAr: 'تهيئة فضاءات لعرض وبيع المنتوجات المحلية بتافوغالت',
        category: 'دعم القطاع الإجتماعي',
        categoryId: 'emploi',
        imageUrl: 'assets/images/projets_extracted/tafoughalt_1.jpg',
        gallery: ["assets/images/projets_extracted/tafoughalt_1.jpg", "assets/images/projets_extracted/tafoughalt_2.jpg", "assets/images/projets_extracted/tafoughalt_3.jpg", "assets/images/projets_extracted/tafoughalt_4.jpg", "assets/images/projets_extracted/tafoughalt_5.jpg", "assets/images/projets_extracted/tafoughalt_6.jpg", "assets/images/projets_extracted/tafoughalt_7.jpg"],
        descriptionFr: 'Aménagement d\'espaces d\'exposition et de vente de produits locaux à Tafoughalt',
        descriptionAr: 'تهيئة فضاءات لعرض وبيع المنتوجات المحلية بتافوغالت',
        cost: '380 000,00 DH',
        location: 'Commune Tafoughalt / جماعة تافوغالت',
        partnersFr: 'Conseil Provincial de Berkane / Commune Tafoughalt / Coopérative Jebal Tafoughalt / Coopérative Al Qimma des femmes rurales de Taghasrout',
        partnersAr: 'مجلس إقليم بركان / جماعة تافوغالت / تعاونية جبال تافوغالت / تعاونية القمة للمرأة القروية بتغاسروت',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 8,
        titleFr: 'Construction de piste (RP 6011 - Douar Dchira)',
        titleAr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image28.jpeg',
        gallery: ["assets/images/projets_extracted/image28.jpeg", "assets/images/projets_extracted/image27.jpeg", "assets/images/projets_extracted/image29.jpeg", "assets/images/projets_extracted/image31.jpeg", "assets/images/projets_extracted/image30.jpeg", "assets/images/projets_extracted/image33.jpeg", "assets/images/projets_extracted/image32.jpeg", "assets/images/projets_extracted/image35.jpeg", "assets/images/projets_extracted/image34.jpeg", "assets/images/projets_extracted/image36.jpeg"],
        descriptionFr: 'Construction de la piste reliant la RP 6011 et Douar Dchira l\'Maarif',
        descriptionAr: 'أشغال بناء المسلك الرابط بين الطريق الإقليمية رقم 6011 ودوار الدشيرة المعاريف',
        cost: '1 061 760,00 DH',
        location: 'Commune Laathamna / جماعة العثامنة',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 9,
        titleFr: 'Protection contre les inondations à Sidi Bouhria (Construction de ponts)',
        titleAr: 'تقدم الأشغال الحماية من الفياضات بمركز سيدي بوهرية "بناء قناطر"',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image38.jpeg',
        gallery: ["assets/images/projets_extracted/image38.jpeg", "assets/images/projets_extracted/image37.jpeg", "assets/images/projets_extracted/image40.jpeg", "assets/images/projets_extracted/image39.jpeg"],
        descriptionFr: 'Protection contre les inondations à Sidi Bouhria (Construction de ponts)',
        descriptionAr: 'تقدم الأشغال الحماية من الفياضات بمركز سيدي بوهرية "بناء قناطر"',
        cost: '1 280 000,00 DH',
        location: 'Commune Sidi Bouhria / جماعة سيدي بوهرية',
        status: 'Réalisé',
        isMain: false
    },

    {
        id: 11,
        titleFr: 'Eau potable - Douars Taichount 2, Tazghine',
        titleAr: 'تزويد دوار تعيشونت 2 و دوار تزغين بوكشوط بالماء الصالح للشرب',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',
        imageUrl: 'assets/images/projets_extracted/image42.jpeg',
        gallery: ["assets/images/projets_extracted/image42.jpeg", "assets/images/projets_extracted/image41.jpeg", "assets/images/projets_extracted/image44.jpeg", "assets/images/projets_extracted/image43.jpeg", "assets/images/projets_extracted/image46.jpeg", "assets/images/projets_extracted/image45.jpeg", "assets/images/projets_extracted/image47.jpeg"],
        descriptionFr: 'Approvisionnement en eau potable (Douars Taichount 2, Tazghine et Bouchouk)',
        descriptionAr: 'تزويد دوار تعيشونت 2 و دوار تزغين  بوكشوط بالماء الصالح للشرب',
        cost: '255 007,20 DH',
        location: 'Commune Zegzel / جماعة زكزل',
        status: 'Réalisé',
        isMain: false
    },

    {
        id: 13,
        titleFr: 'Aménagement salle polyvalente Chouihia',
        titleAr: 'تجهيز قاعة متعددة الاختصاصات بإعدادية الشويحية',
        category: 'دعم القطاع الثقافي و الرياضي',
        imageUrl: 'assets/images/projets_extracted/image50.jpeg',
        gallery: ["assets/images/projets_extracted/image50.jpeg", "assets/images/projets_extracted/image49.jpeg", "assets/images/projets_extracted/image51.jpeg"],
        descriptionFr: 'Construction d\'une salle polyvalente au collège Chouihia',
        descriptionAr: 'تجهيز قاعة متعددة الاختصاصات بإعدادية الشويحية',
        cost: '603 428,00 DH',
        location: 'Commune Chouihia / جماعة الشويحية',
        partnersFr: 'Direction Provinciale de l\'Education et de la Formation Berkane, Commune Chouihia',
        partnersAr: 'المديرية الإقليمية للتربية والتكوين بركان، جماعة الشويحية',
        partnerImages: ['assets/images/partners/commune_chouihia.jpeg'],
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 14,
        titleFr: 'Pont sur Oued Khemis',
        titleAr: 'أشغال بناء قنطرة على واد الخميس بدوار بوغريبة',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image53.jpeg',
        gallery: ["assets/images/projets_extracted/image53.jpeg", "assets/images/projets_extracted/image52.jpeg", "assets/images/projets_extracted/image54.jpeg"],
        descriptionFr: 'Construction d\'un pont sur l\'Oued Khemis à Douar Boughriba',
        descriptionAr: 'أشغال بناء قنطرة  على واد الخميس بدوار بوغريبة',
        cost: '187 236,00 DH',
        location: 'Commune Boughriba / جماعة بوغريبة',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 15,
        titleFr: 'Construction Espace Tissu Associatif',
        titleAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        category: 'دعم القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image56.jpeg',
        gallery: ["assets/images/projets_extracted/image56.jpeg", "assets/images/projets_extracted/image55.jpeg", "assets/images/projets_extracted/image57.jpeg", "assets/images/projets_extracted/image58.jpeg", "assets/images/projets_extracted/image60.jpeg", "assets/images/projets_extracted/image59.jpeg", "assets/images/projets_extracted/image62.jpeg", "assets/images/projets_extracted/image61.jpeg", "assets/images/projets_extracted/image63.jpeg"],
        descriptionFr: 'Construction et équipement de l\'Espace du Tissu Associatif',
        descriptionAr: 'بناء وتجهيز فضاء النسيج الجمعوي',
        cost: '600 000,00 DH',
        location: 'Commune Ain Reggada / جماعة عين الركادة',
        partnersFr: 'Commune Ain Reggada',
        partnersAr: 'جماعة عين ركادة',
        partnerImages: ['assets/images/partners/commune_ain_raggada.jpeg'],
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 16,
        titleFr: 'Electrification terrain foot Ain Reggada',
        titleAr: 'تزويد ملعب كرة القدم بالكهرباء بجماعة عين الركادة',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',
        imageUrl: 'assets/images/projets_extracted/image65.jpeg',
        gallery: ["assets/images/projets_extracted/image65.jpeg", "assets/images/projets_extracted/image64.jpeg"],
        descriptionFr: 'Electrification du terrain de football de la commune Ain Reggada',
        descriptionAr: 'تزويد ملعب كرة القدم بالكهرباء بجماعة عين الركادة',
        cost: '200 000,00 DH',
        location: 'Commune Ain Reggada / جماعة عين الركادة',
        partnersFr: 'Commune Ain Reggada',
        partnersAr: 'جماعة عين الركادة',
        partnerImages: ['assets/images/partners/commune_ain_raggada.jpeg'],
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 17,
        titleFr: 'Eclairage public Avenue Mohammed V (Ahfir)',
        titleAr: 'أشغال الانارة العمومية شارع محمد الخامس بجماعة أحفير',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',

        imageUrl: 'assets/images/projets_extracted/ahfir_eclairage_3.jpg',
        gallery: ["assets/images/projets_extracted/ahfir_eclairage_3.jpg", "assets/images/projets_extracted/ahfir_eclairage_1.jpg", "assets/images/projets_extracted/ahfir_eclairage_2.jpg"],
        descriptionFr: 'Travaux d\'éclairage public sur l\'Avenue Mohammed V à Ahfir',
        descriptionAr: 'أشغال الانارة العمومية  شارع محمد الخامس بجماعة أحفير',
        cost: '2 633 983,44 DH',
        location: 'Commune Ahfir / جماعة أحفير',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 18,
        titleFr: 'Aménagements établissements scolaires (Ahfir)',
        titleAr: 'أشغال التهيئة الخارجية للمؤسسات التعليمية بجماعة أحفير',
        category: 'دعم القطاع التعليمي',
        imageUrl: 'assets/images/projets_extracted/image71.jpeg',
        gallery: ["assets/images/projets_extracted/image71.jpeg", "assets/images/projets_extracted/image70.jpeg", "assets/images/projets_extracted/image73.jpeg", "assets/images/projets_extracted/image72.jpeg"],
        descriptionFr: 'Aménagements extérieurs des établissements scolaires à Ahfir',
        descriptionAr: 'أشغال التهيئة الخارجية للمؤسسات التعليمية بجماعة أحفير',
        cost: '456 031,68 DH',
        location: 'Commune Ahfir / جماعة أحفير',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 19,
        titleFr: 'Eau potable Douar Takrourine (Fezouane)',
        titleAr: 'أشغال تزويد دوار تكرورين-سيدي علي بن يخلف بالماء الصالح للشرب جماعة فزوان',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',
        imageUrl: 'assets/images/projets_extracted/image75.jpeg',
        gallery: ["assets/images/projets_extracted/image75.jpeg", "assets/images/projets_extracted/image74.jpeg", "assets/images/projets_extracted/image77.jpeg", "assets/images/projets_extracted/image76.jpeg"],
        descriptionFr: 'Approvisionnement en eau potable du Douar Takrourine - Sidi Ali Ben Yakhlef (Fezouane)',
        descriptionAr: 'أشغال تزويد دوار تكرورين-سيدي علي بن يخلف بالماء الصالح للشرب جماعة فزوان سيدي علي بن يخلف',
        cost: '130 080,00 DH',
        location: 'Commune Fezouane / جماعة فزوان',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 20,
        titleFr: 'Piste Ain Zebda - Beni Moussa',
        titleAr: 'انجاز المسلك المؤدي من عين الزبدة إلى بني موسى بجماعة مداغ',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image79.jpeg',
        gallery: ["assets/images/projets_extracted/image79.jpeg", "assets/images/projets_extracted/image78.jpeg", "assets/images/projets_extracted/image81.jpeg", "assets/images/projets_extracted/image80.jpeg"],
        descriptionFr: 'Réalisation de la piste reliant Ain Zebda à Beni Moussa (Madagh)',
        descriptionAr: 'انجاز المسلك المؤدي من عين الزبدة إلى بني موسى بجماعة مداغ',
        cost: '219 000,00 DH',
        location: 'Commune Madagh / جماعة مداغ',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 21,
        titleFr: 'Financement pistes rurales',
        titleAr: 'تمويل و فتح و تهيئة المسالك القروية',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image83.jpeg',
        gallery: ["assets/images/projets_extracted/image83.jpeg", "assets/images/projets_extracted/image82.jpeg", "assets/images/projets_extracted/image85.jpeg", "assets/images/projets_extracted/image84.jpeg", "assets/images/projets_extracted/image86.jpeg", "assets/images/projets_extracted/image88.jpeg", "assets/images/projets_extracted/image87.jpeg", "assets/images/projets_extracted/image90.jpeg", "assets/images/projets_extracted/image89.jpeg", "assets/images/projets_extracted/image92.jpeg", "assets/images/projets_extracted/image91.jpeg"],
        descriptionFr: 'Financement et aménagement de pistes rurales',
        descriptionAr: 'تمويل و فتح و تهيئة المسالك القروية',
        cost: '5 543 489,75 DH',
        location: 'Fezouane, Aghbal, Zegzel / فزوان، أغبال، زكزل',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 22,
        titleFr: 'Curage Oueds Cherraa et Ouartas',
        titleAr: 'عملية تتبع وتسيير أشغال تنقية واد شراعة وواد ورطاس',
        category: 'دعم القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image94.jpeg',
        gallery: ["assets/images/projets_extracted/image94.jpeg", "assets/images/projets_extracted/image93.jpeg", "assets/images/projets_extracted/image95.jpeg", "assets/images/projets_extracted/image96.jpeg"],
        descriptionFr: 'Suivi et gestion des travaux de curage des Oueds Cherraa et Ouartas',
        descriptionAr: 'عملية تتبع وتسيير أشغال تنقية واد شراعة وواد ورطاس ',
        cost: 'Non spécifié / غير محدد',
        location: 'Commune de Berkane / جماعة بركان',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 23,
        titleFr: 'Acquisition d\'un véhicule utilitaire pour l\'association Nomidia',
        titleAr: 'اقتناء سيارة نفعية لفائدة نوميديا',
        category: 'دعم القطاع الإجتماعي',
        categoryId: 'emploi',
        imageUrl: 'assets/images/projets_extracted/image97.jpeg',
        gallery: ["assets/images/projets_extracted/image97.jpeg"],
        descriptionFr: 'Acquisition d\'un véhicule utilitaire pour l\'association Nomidia',
        descriptionAr: 'اقتناء سيارة نفعية لفائدة نوميديا',
        cost: '150 000,00 DH',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 24,
        titleFr: 'Campagne correction vue élèves',
        titleAr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        category: 'دعم القطاع الصحي',
        imageUrl: 'assets/images/projets_extracted/image99.jpeg',
        gallery: ["assets/images/projets_extracted/image99.jpeg", "assets/images/projets_extracted/image98.jpeg", "assets/images/projets_extracted/image101.jpeg", "assets/images/projets_extracted/image100.jpeg", "assets/images/projets_extracted/image103.jpeg", "assets/images/projets_extracted/image102.jpeg", "assets/images/projets_extracted/image105.jpeg", "assets/images/projets_extracted/image104.jpeg"],
        descriptionFr: 'Organisation d\'une campagne médicale ophtalmologique pour les élèves',
        descriptionAr: 'تنظيم حملة طبية لقياس وتصحيح البصر للممدرسين  بإقليم بركان',
        cost: '150 000,00 DH',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 25,
        titleFr: 'Pont Oued Besbas',
        titleAr: 'بناء قنطرة على واد البسباس دوار اولاد الحاج جماعة زكزل',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image107.jpeg',
        gallery: ["assets/images/projets_extracted/image107.jpeg", "assets/images/projets_extracted/image106.jpeg"],
        descriptionFr: 'Construction d\'un pont sur l\'Oued Besbas (Douar Ouled El Haj, Zegzel)',
        descriptionAr: 'بناء قنطرة على واد البسباس دوار اولاد الحاج جماعة زكزل',
        cost: '21 000,00 DH',
        location: 'Commune Zegzel / جماعة زكزل',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 26,
        titleFr: 'Eau potable Douar Zaara',
        titleAr: 'تزويد دوار الزعارة لوطا بالماء الشروب بجماعة بوغريبة',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',
        imageUrl: 'assets/images/projets_extracted/image109.jpeg',
        gallery: ["assets/images/projets_extracted/image109.jpeg", "assets/images/projets_extracted/image108.jpeg", "assets/images/projets_extracted/image110.jpeg"],
        descriptionFr: 'Approvisionnement en eau potable du Douar Zaara Louta (Boughriba)',
        descriptionAr: 'تزويد  دوار  الزعارة لوطا بالماء الشروب بجماعة بوغريبة',
        cost: '86 403,48 DH',
        location: 'Commune Boughriba / جماعة بوغريبة',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 27,
        titleFr: 'Acquisition de 10 bus de transport scolaire pour le Conseil Provincial',
        titleAr: 'اقتناء 10 حافلات للنقل المدرسي لفائدة المجلس الإقليمي لبركان',
        category: 'دعم القطاع التعليمي',
        categoryId: 'emploi',
        imageUrl: 'assets/images/projets_extracted/image112.png',
        gallery: ["assets/images/projets_extracted/image112.png", "assets/images/projets_extracted/image111.jpeg"],
        descriptionFr: 'Acquisition de 10 bus de transport scolaire pour le Conseil Provincial',
        descriptionAr: 'اقتناء 10 حافلات للنقل المدرسي لفائدة المجلس الإقليمي لبركان',
        cost: '3 535 004,04 DH',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 4,
        titleFr: 'Construction du Noyau Universitaire',
        titleAr: 'بناء النواة الجامعية',
        category: 'دعم القطاع التعليمي',
        imageUrl: 'assets/images/projets_extracted/university_hub_1.jpg',
        gallery: ["assets/images/projets_extracted/university_hub_1.jpg", "assets/images/projets_extracted/university_hub_2.jpg", "assets/images/projets_extracted/university_hub_3.jpg", "assets/images/projets_extracted/university_hub_4.jpg"],
        descriptionFr: 'Construction du Noyau Universitaire',
        descriptionAr: 'بناء النواة الجامعية',
        cost: '4 332 150,00 DH',
        location: 'Commune Sidi Slimane Charraa / جماعة سيدي سليمان شراعة',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 28,
        titleFr: 'Etude et réalisation d\'ouvrage d\'art sur Oued Ouartas',
        titleAr: 'تمويل و انجاز الدراسة التعريفية , التمهيدية و التنفيدية لمنشأة فنية على واد ورطاس الرابطة بين حي ورطاس و برج واولوت',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/wartass_bridge_5.jpg',
        gallery: ["assets/images/projets_extracted/wartass_bridge_1.jpg", "assets/images/projets_extracted/wartass_bridge_2.jpg", "assets/images/projets_extracted/wartass_bridge_3.jpg", "assets/images/projets_extracted/wartass_bridge_4.jpg", "assets/images/projets_extracted/wartass_bridge_5.jpg"],
        descriptionFr: 'Etude et réalisation d\'ouvrage d\'art sur Oued Ouartas (liaison Hay Ouartas - Borj Waoulout)',
        descriptionAr: 'تمويل و انجاز الدراسة التعريفية , التمهيدية و التنفيدية لمنشأة فنية على واد ورطاس الرابطة بين حي ورطاس و برج واولوت',
        cost: '67 400 000,00 DH',
        location: 'Commune de Berkane / جماعة بركان',
        partnersFr: 'Ministère de l\'Equipement et de l\'Eau / Commune Zegzel',
        partnersAr: 'وزارة التجهيز و الماء / جماعة زكزل',
        partnerImages: ['assets/images/partners/ministere_equipement.jpeg'],
        status: 'En cours',
        isMain: false
    },
    {
        id: 29,
        titleFr: 'Complexe éducatif et sportif Zegzel',
        titleAr: 'بناء و تجهيز المركب التربوي و الرياضي و الصحي بجماعة زكزل',
        category: 'دعم القطاع الثقافي و الرياضي',
        imageUrl: 'assets/images/projets_extracted/zegzel_complex_1.jpg',
        gallery: ["assets/images/projets_extracted/zegzel_complex_1.jpg", "assets/images/projets_extracted/zegzel_complex_2.jpg", "assets/images/projets_extracted/zegzel_complex_3.jpg", "assets/images/projets_extracted/zegzel_complex_4.jpg", "assets/images/projets_extracted/zegzel_complex_5.jpg", "assets/images/projets_extracted/zegzel_complex_6.jpg"],
        descriptionFr: 'Construction et équipement du complexe éducatif, sportif et de santé à Zegzel',
        descriptionAr: 'بناء و تجهيز المركب التربوي و الرياضي و الصحي بجماعة زكزل',
        cost: '20 000 000,00 DH (تهيئة و المساهمة في توفير الوعاء العقاري)',
        location: 'Commune Zegzel / جماعة زكزل',
        status: 'En cours',
        isMain: false
    },
    {
        id: 30,
        titleFr: 'Aménagement de pistes rurales',
        titleAr: 'تهيئة المسالك بالإقليم',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image130.jpeg',
        gallery: ["assets/images/projets_extracted/image130.jpeg", "assets/images/projets_extracted/image129.jpeg", "assets/images/projets_extracted/image131.jpeg", "assets/images/projets_extracted/image133.jpeg", "assets/images/projets_extracted/image132.jpeg", "assets/images/projets_extracted/image134.jpeg"],
        descriptionFr: 'Aménagement de pistes rurales dans la province',
        descriptionAr: 'تهيئة المسالك بالإقليم',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 31,
        titleFr: 'Traitement points noirs pistes',
        titleAr: 'تهيئة المسالك و تنقية النقط السوداء بالإقليم',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image136.jpeg',
        gallery: ["assets/images/projets_extracted/image136.jpeg", "assets/images/projets_extracted/image135.jpeg", "assets/images/projets_extracted/image138.jpeg", "assets/images/projets_extracted/image137.jpeg", "assets/images/projets_extracted/image142.jpeg", "assets/images/projets_extracted/image141.jpeg", "assets/images/projets_extracted/image143.jpeg", "assets/images/projets_extracted/image140.jpeg", "assets/images/projets_extracted/image139.jpeg"],
        descriptionFr: 'Aménagement de pistes et traitement des points noirs',
        descriptionAr: 'تهيئة المسالك و تنقية  النقط  السوداء بالإقليم',
        cost: 'Non spécifié / غير محدد',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Réalisé',
        isMain: false
    },

    {
        id: 33,
        titleFr: 'Etude de passage souterrain piéton au PK 515+280 et RN 2',
        titleAr: 'دراسة ممر الراجلين تحت أرضي على مستوى النقطة الكيلوميترية 515+280 و الطريق الوطنية رقم 2 بجماعة بركان',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image28.jpeg',
        gallery: ["assets/images/projets_extracted/image28.jpeg"],
        descriptionFr: 'Etude de passage souterrain piéton au PK 515+280',
        descriptionAr: 'دراسة ممر الراجلين تحت أرضي على مستوى النقطة الكيلوميترية 515+280 و الطريق الوطنية رقم 2 بجماعة بركان (الدراسة التقنية)',
        cost: '4 200 000,00 DH (Global) / 103 000,00 DH (Etude)',
        location: 'Commune de Berkane / جماعة بركان',
        status: 'Réalisé',
        isMain: true
    },
    {
        id: 34,
        titleFr: 'Achèvement et équipement de l\'abattoir communal de Berkane',
        titleAr: 'اتمام بناء و تجهيز المجزرة العصرية بجماعة بركان',
        category: 'دعم القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/battoire_1.jpeg',
        gallery: ["assets/images/projets_extracted/battoire_1.jpeg", "assets/images/projets_extracted/battoire_2.jpeg", "assets/images/projets_extracted/battoire_3.jpeg"],
        descriptionFr: 'Achèvement et équipement de l\'abattoir communal de Berkane',
        descriptionAr: 'اتمام بناء و تجهيز المجزرة العصرية بجماعة بركان',
        cost: '29 067 500,00 DH',
        location: 'Commune de Berkane / جماعة بركان',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 35,
        titleFr: 'Construction d\'un ouvrage d\'art (RP 6000 - Douar Arbouch)',
        titleAr: 'اشغال بناء منشأة فنية على الطريق الرابط بين الطريق الاقليمية 6000 و دوار عربوش عبر اعيدين بجماعة اغبال',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image28.jpeg',
        gallery: ["assets/images/projets_extracted/image28.jpeg"],
        descriptionFr: 'Construction d\'un ouvrage d\'art (RP 6000 - Douar Arbouch)',
        descriptionAr: 'اشغال بناء منشأة فنية على الطريق الرابط بين الطريق الاقليمية 6000 و دوار عربوش عبر اعيدين بجماعة اغبال',
        cost: '360 210,00 DH',
        location: 'Commune Aghbal / جماعة أغبال',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 36,
        titleFr: 'Extension du réseau d\'eau potable (Douar Ouled Amri - Laathamna)',
        titleAr: 'أشغال تمديد شبكة الماء الصالح للشرب دوار اولاد العامري بالماء الشروب بجماعة لعثامنة',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',
        imageUrl: 'assets/images/projets_extracted/image42.jpeg',
        gallery: ["assets/images/projets_extracted/image42.jpeg"],
        descriptionFr: 'Extension du réseau d\'eau potable (Douar Ouled Amri - Laathamna)',
        descriptionAr: 'أشغال تمديد شبكة الماء الصالح للشرب دوار اولاد العامري بالماء الشروب بجماعة لعثامنة',
        cost: '128 772,00 DH',
        location: 'Commune Laathamna / جماعة لعثامنة',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 37,
        titleFr: 'Construction d\'un pont sur Oued Ihmouten (Zegzel)',
        titleAr: 'بناء قنطرة على واد إحموتن جماعة زكزل',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image53.jpeg',
        gallery: ["assets/images/projets_extracted/image53.jpeg"],
        descriptionFr: 'Construction d\'un pont sur Oued Ihmouten (Zegzel)',
        descriptionAr: 'بناء قنطرة على واد إحموتن جماعة زكزل',
        cost: '80 000,00 DH',
        location: 'Commune Zegzel / جماعة زكزل',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 38,
        titleFr: 'Aménagement d\'un terrain de proximité (Chouihia)',
        titleAr: 'تهيئة ملعب رياضي للقرب بجماعة الشويحية',
        category: 'دعم القطاع الثقافي و الرياضي',
        imageUrl: 'assets/images/projets_extracted/image51.jpeg',
        gallery: ["assets/images/projets_extracted/image51.jpeg"],
        descriptionFr: 'Aménagement d\'un terrain de proximité (Chouihia)',
        descriptionAr: 'تهيئة ملعب رياضي للقرب بجماعة الشويحية',
        cost: '40 000,00 DH',
        location: 'Commune Chouihia / جماعة الشويحية',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 39,
        titleFr: 'Approvisionnement en eau potable Douar Ouled Bouabd',
        titleAr: 'تزويد دوار أولاد بوعبد السيد بالماء الشروب بجماعة بوغريبة',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',
        imageUrl: 'assets/images/projets_extracted/image109.jpeg',
        gallery: ["assets/images/projets_extracted/image109.jpeg"],
        descriptionFr: 'Approvisionnement en eau potable Douar Ouled Bouabd',
        descriptionAr: 'تزويد دوار أولاد بوعبد السيد بالماء الشروب بجماعة بوغريبة',
        cost: '300 000,00 DH',
        location: 'Commune Boughriba / جماعة بوغريبة',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 40,
        titleFr: 'Equipement du centre de l\'association Afaq (Madagh)',
        titleAr: 'تجهيز مركز جمعية أفاق للأطفال ذوي التوحد بمداغ',
        category: 'دعم القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image6.jpeg',
        gallery: ["assets/images/projets_extracted/image6.jpeg"],
        descriptionFr: 'Equipement du centre de l\'association Afaq (Madagh)',
        descriptionAr: 'تجهيز مركز جمعية أفاق للأطفال ذوي التوحد بمداغ',
        cost: '45 000,00 DH',
        location: 'Commune Madagh / جماعة مداغ',
        status: 'Programmé',
        isMain: false
    },
    {
        id: 41,
        titleFr: 'Electrification de maisons à Madagh (Hay Salam, Ouled Amri...)',
        titleAr: 'كهربة بعض المنازل بدواوير : حي السلام - اولاد العامري – العدادغة - الشنن اولاد عبدالرحمان بجماعة مداغ',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',
        imageUrl: 'assets/images/projets_extracted/image17.jpeg',
        gallery: ["assets/images/projets_extracted/image17.jpeg"],
        descriptionFr: 'Electrification de maisons à Madagh',
        descriptionAr: 'كهربة بعض المنازل بدواوير : حي السلام - اولاد العامري – العدادغة - الشنن اولاد عبدالرحمان بجماعة مداغ',
        cost: '87 142,80 DH',
        location: 'Commune Madagh / جماعة مداغ',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 42,
        titleFr: 'Extension de l\'éclairage public (Douar Ouled Amri - Madagh)',
        titleAr: 'مشروع توسيع الانارة العمومية : دوار اولاد العامري حي السلام بجماعة مداغ',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',
        imageUrl: 'assets/images/projets_extracted/image16.jpeg',
        gallery: ["assets/images/projets_extracted/image16.jpeg"],
        descriptionFr: 'Extension de l\'éclairage public (Douar Ouled Amri - Madagh)',
        descriptionAr: 'مشروع توسيع الانارة العمومية : دوار اولاد العامري حي السلام بجماعة مداغ',
        cost: '100 000,00 DH',
        location: 'Commune Madagh / جماعة مداغ',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 43,
        titleFr: 'Construction d\'un ouvrage d\'art à Saidia',
        titleAr: 'إنجاز منشأة فنية بحي الشراربة',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image28.jpeg',
        gallery: ["assets/images/projets_extracted/image28.jpeg"],
        descriptionFr: 'Construction d\'un ouvrage d\'art à Saidia',
        descriptionAr: 'إنجاز منشأة فنية بحي الشراربة',
        cost: '145 000,00 DH',
        location: 'Commune Saidia / جماعة السعيدية',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 44,
        titleFr: 'Gestion du transport scolaire',
        titleAr: 'تدبير قطاع النقل المدرسي باقليم بركان',
        category: 'دعم القطاع التعليمي',
        imageUrl: 'assets/images/projets_extracted/image112.png',
        gallery: ["assets/images/projets_extracted/image112.png"],
        descriptionFr: 'Gestion du transport scolaire à Berkane',
        descriptionAr: 'تدبير قطاع النقل المدرسي باقليم بركان (2021: 750k, 2022: 250k, 2023: 1.5M)',
        cost: '2 500 000,00 DH',
        location: 'Province de Berkane / إقليم بركان',
        status: 'En cours',
        isMain: false
    },
    {
        id: 45,
        titleFr: 'Achat de carburant',
        titleAr: 'شراء الوقود لفائدة المجلس الإقليمي لبركان',
        category: 'دعم القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image97.jpeg',
        gallery: ["assets/images/projets_extracted/image97.jpeg"],
        descriptionFr: 'Achat de carburant pour le Conseil Provincial',
        descriptionAr: 'شراء الوقود لفائدة المجلس الإقليمي لبركان',
        cost: '170 316,30 DH',
        location: 'Commune de Berkane / جماعة بركان',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 46,
        titleFr: 'Eclairage public Zegzel (Projet Ouartas)',
        titleAr: 'اشغال الانارة العمومية بالنسبة للجزء المتعلق بجماعة زكزل و إنجاز الاشغال',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',
        imageUrl: 'assets/images/projets_extracted/image113.jpeg',
        gallery: ["assets/images/projets_extracted/image113.jpeg"],
        descriptionFr: 'Travaux d\'éclairage public à Zegzel',
        descriptionAr: 'اشغال الانارة العمومية بالنسبة للجزء المتعلق بجماعة زكزل و إنجاز الاشغال',
        cost: '1 000 000,00 DH',
        location: 'Commune Zegzel / جماعة زكزل',
        status: 'Programmé',
        isMain: false
    },
    {
        id: 47,
        titleFr: 'Aménagement extérieur et éclairage (Passage souterrain)',
        titleAr: 'أشغال التهيئة الخارجية والانارة العمومية للمشروع (ممر تحت أرضي)',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/passage_souterrain_1.jpg',
        gallery: ["assets/images/projets_extracted/passage_souterrain_1.jpg", "assets/images/projets_extracted/passage_souterrain_2.jpg"],
        descriptionFr: 'Aménagements extérieurs et éclairage du projet (Passage souterrain)',
        descriptionAr: 'أشغال التهيئة الخارجية والانارة العمومية للمشروع',
        cost: '300 000,00 DH',
        location: 'Commune de Berkane / جماعة بركان',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 48,
        titleFr: 'Location de camions 18m3',
        titleAr: 'كراء شاحنات 18m3 لنقل المواد الضرورية لتهيئة المسالك بالإقليم',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image83.jpeg',
        gallery: ["assets/images/projets_extracted/image83.jpeg"],
        descriptionFr: 'Location de camions pour aménagement des pistes',
        descriptionAr: 'كراء شاحنات 18m3 لنقل المواد الضرورية لتهيئة المسالك بالإقليم',
        cost: '393 960,60 DH',
        location: 'Province de Berkane / إقليم بركان',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 49,
        titleFr: 'Canalisation eaux usées BELHYDROS',
        titleAr: 'مشروع إنجاز قناة جر المياه العادمة المعالجة في محطة التصفية التابعة لشركة BELHYDROS',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',
        imageUrl: 'assets/images/projets_extracted/image11.jpeg',
        gallery: ["assets/images/projets_extracted/image11.jpeg"],
        descriptionFr: 'Réalisation canalisation des eaux usées (BELHYDROS)',
        descriptionAr: 'مشروع إنجاز قناة جر المياه العادمة المعالجة في محطة التصفية التابعة لشركة BELHYDROS',
        cost: '7 000 000,00 DH',
        location: 'Province de Berkane / إقليم بركان',
        status: 'En cours',
        isMain: false
    },
    {
        id: 50,
        titleFr: 'Equipement forage solaire Ouled Abdelkarim',
        titleAr: 'أشغال تجهيز ثقب مائي بنظام الضخ بالطاقة الشمسية بدوار أولاد عبد الكريم بجماعة تافوغالت',
        category: 'تزويد العالم القروي بالكهرباء و الماء الصالح للشرب',
        imageUrl: 'assets/images/projets_extracted/image109.jpeg',
        gallery: ["assets/images/projets_extracted/image109.jpeg"],
        descriptionFr: 'Equipement de forage solaire à Ouled Abdelkarim (Tafoughalt)',
        descriptionAr: 'أشغال تجهيز ثقب مائي بنظام الضخ بالطاقة الشمسية بدوار أولاد عبد الكريم بجماعة تافوغالت',
        cost: '218 656,80 DH',
        location: 'Commune Tafoughalt / جماعة تافوغالت',
        status: 'En cours',
        isMain: false
    },

    {
        id: 52,
        titleFr: 'Aménagement archives et buvette CP',
        titleAr: 'تهيئة الأرشيف و مقصف بمقر المجلس الإقليمي لبركان',
        category: 'دعم القطاع الإجتماعي',
        imageUrl: 'assets/images/projets_extracted/image6.jpeg',
        gallery: ["assets/images/projets_extracted/image6.jpeg"],
        descriptionFr: 'Aménagement des archives et de la buvette du Conseil Provincial',
        descriptionAr: 'تهيئة الأرشيف و مقصف بمقر المجلس الإقليمي لبركان',
        cost: '155 278,76 DH',
        location: 'Commune de Berkane / جماعة بركان',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 53,
        titleFr: 'Equipement salle de lecture Rislane',
        titleAr: 'تجهيز قاعة للمطالعة بجماعة رسلان',
        category: 'دعم القطاع الثقافي و الرياضي',
        imageUrl: 'assets/images/projets_extracted/image50.jpeg',
        gallery: ["assets/images/projets_extracted/image50.jpeg"],
        descriptionFr: 'Equipement de la salle de lecture à Rislane',
        descriptionAr: 'تجهيز قاعة للمطالعة بجماعة رسلان',
        cost: '100 000,00 DH',
        location: 'Commune Rislane / جماعة رسلان',
        status: 'Réalisé',
        isMain: false
    },
    {
        id: 54,
        titleFr: 'Pont Oued Moulouya (Moulay Ali - Chouihia)',
        titleAr: 'انجاز قنطرة على واد ملوية –حامة مولاي علي- الشويحية',
        category: 'إنجاز و صيانة المسالك القروية',
        imageUrl: 'assets/images/projets_extracted/image53.jpeg',
        gallery: ["assets/images/projets_extracted/image53.jpeg"],
        descriptionFr: 'Réalisation d\'un pont sur l\'Oued Moulouya (Moulay Ali - Chouihia)',
        descriptionAr: 'انجاز قنطرة على واد ملوية –حامة مولاي علي- الشويحية',
        cost: '250 000,00 DH (Contribution)',
        location: 'Commune Chouihia / جماعة الشويحية',
        status: 'Programmé',
        isMain: false
    }
];